<a href="https://colab.research.google.com/github/RovisLab/Course_AI/blob/main/IA_lab_1_Introducere_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laborator 1: Introducere în Python; Algebră liniară
În acest laborator se discută câteva aspecte teoretice generale despre limbajul de programare Python, punându-se accentul pe funcționalități utilizate în general în domeniul de Învățare Automată.

Sunt parcurse câteva exemple de bază pentru ilustrarea conceptelor generale Python:
* liste
* dicționare
* funcții
* clase

De asemenea, sunt prezentate operații de algebră liniară, realizate cu ajutorul modulului numpy.

# Tipuri de date
Python este un limbaj de programare interpretat, utilizat într-o varietate mare de domenii, dintre care se remarcă data science, machine learning, web development, etc.
Fiind un limbaj de nivel înalt, este adecvat scrierii de prototipuri rapide pentru aplicații. Spre exemplu, este mult mai ușor să dezvoltăm un prototip al unui algoritm de inteligență artificială în Python decât în alte limbaje consacrate.
Mecanismul de reutilizare al codului folosit în Python este sub forma modulelor pe care utilizatorul le instalează, apoi le importă și le utilizează în cod:

```
import numpy as np

x = np.zeros((3, 3), dtype=np.uint8)
print(x)
```

Exemplul anterior importă modulul denumit ***numpy***, creează un obiect de tip ***numpy array*** având dimensiunea $(3, 3)$ și îl inițializează cu ***zero***.

În general, codul Python destinat reutilizării de către alți dezvoltatori este încapsulat în clase, care mai departe sunt organizate în pachete denumite module.

**Tipuri de date**

În Python, variabilele se declară și definesc simultan:


```
>>> x = 11
>>> x
11
```
Spre deosebire de alte limbaje de programare, nu este necesar să specificăm tipul variabilei în cadrul declarării sale.
De asemenea, o variabilă poate fi suprascrisă:


```
>>> x = 11
>>> x = "Ion"
>>> x
'Ion'
```
Se poate determina tipul unei variabile în Python apelând metoda **type()**:


```
>>> x = "Ion"
>>> type(x)
<class 'str'>
```

Variabilele pot fi de următoarele tipuri:
```
Text:	str
Numerice:	int, float, complex
Tipuri secvențiale:	list, tuple, range
Dicționare:	dict
Seturi:	set, frozenset
Booleene:	bool
Tipuri binare:	bytes, bytearray, memoryview
Tipul None:	NoneType
```
Tipuri întregi:


```
>>> x = 15
>>> print(x)
15
```

Tipuri floating point:

```
>>> x = 1.5
>>> print(x)
1.5
```

Tipuri complexe:
```
>>> x = 1 + 5j
>>> print(x)
(1+5j)
```

Liste:
```
>>> x = [1, 2, 3, 4, 5]
>>> print(x)
[1, 2, 3, 4, 5]
```

Tupluri:
```
>>> x = (1,2,3,4,5)
>>> print(x)
(1, 2, 3, 4, 5)
```
**Notă** diferența principală dintre un tuplu și o listă este aceea că tuplul este **imutabil**.

Dicționare:

```
>>> x = {1: "ana", 2: "are", 3: "mere"}
>>> print(x)
{1: 'ana', 2: 'are', 3: 'mere'}
```
Dicționarele sunt colecții de tupluri de forma (cheie, valoare), în care valorile se accesează prin intermediul cheii.

Seturi:

```
>>> x = {"ana", "are", "mere", "mere"}
>>> print(x)
{'mere', 'are', 'ana'}
```
Seturile reprezintă colecții de date imutabile, neordonate, **care nu permit valori duplicate**.

Booleene:
```
>>> x = True
>>> print(x)
True
>>> print(int(x))
1
>>> y = False
>>> print(y)
False
>>> print(int(y))
0
```
A se observa faptul că valoarea de adevăr True este echivalentă cu valoarea 1, iar False cu valoarea 0.

Tipuri binare (bytes):
```
>>> x = b"\x01\x02"
>>> print(x)
b'\x01\x02'
>>> type(x)
<class 'bytes'>
```

# Exemple
1. Să se creeze o listă de 20 de elemente ordonate crescător $x=[1,..., 20]$.
2. Să se afișeze elementele listei.
3. Să se afișeze al patrulea element al listei.
4. Să se afișeze toate elementele din listă mai mari decât 7.
5. Să se realizeze același exercițiu, însă folosind *list comprehension*.
6. Să se afișeze elementele din listă având indexul între 10 și 20.
7. Să se realizeze același exercițiu, însă folosind *list slicing*.
8. Să se afișeze din listă elementele din listă dintre indecșii 5 și 10 folosind list slicing.
9. Să se afișeze primele 5 elemente din listă utilizând list slicing.
10. Să se afișeze ultimul element din listă.
11. Să se creeze încă o listă de 5 elemente $x_2=[21, 22, 23, 24, 25]$ și să se realizeze alipirea celor două liste.
12. Să se șteargă primul element din lista $x$ și să se afișeze aceasta ulterior.

In [ ]:
# ex1
x = [i for i in range(1, 21)]

# ex2
print(x)

# ex3
print(x[3])

# ex4
for i in range(len(x)):
  if x[i] > 7:
    print(x[i])

# ex5
print([elem for elem in x if elem > 7])

# ex6
for i in range(10, len(x)):
  print(x[i])

# ex7
print(x[10:])

# ex8
print(x[5:10])

# ex9
print(x[:5])

# ex10
print(x[-1])

# ex11
x2 = [21, 22, 23, 24, 25]
print(x + x2)

# ex12
x.pop(0)
print(x)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
4
8
9
10
11
12
13
14
15
16
17
18
19
20
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
11
12
13
14
15
16
17
18
19
20
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5]
20
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


# Exerciții cu dicționare

Se dă următorul dicționar:


```
d = {1: "Maria", 2: "Ion", 3: "Vasile", 4: "Gigel",
     5: "Stefan", 6: "Alex", 7: "Gheorghe", 8: "Irina",
     9: "Elena", 10: "Matei"}
```
Se vor rezolva următoarele:


1.   Afișarea elementului având cheia 2.
2.   Afișarea tuturor elementelor având o cheie $ k \leq 5$.
3.   Inserarea unei înregistrări $(k, v)$ în dicționar, unde cheia $k = 11$, iar valoarea $v="Ionut"$ și afișarea ulterioară a dicționarului.
4.   Schimbarea elementului având cheia 9 în $"Ionela"$ și afișarea ulterioară a dicționarului.
5.   Afișarea numărului de elemente conținute de dicționar.
6.   Ștergerea elementului care are cheia $k=10$ din dicționar și afișarea ulterioară a acestuia, respectiv afișarea lungimii sale.


In [ ]:
d = {1: "Maria", 2: "Ion", 3: "Vasile", 4: "Gigel",
     5: "Stefan", 6: "Alex", 7: "Gheorghe", 8: "Irina",
     9: "Elena", 10: "Matei"}

# ex1
print(d[2])

# ex2
for k in d:
  if k <= 5:
    print(d[k])

# ex3
d[11] = "Ionut"
print(d)

# ex4
d[9] = "Ionela"
print(d)

# ex5
print(len(d))

# ex6
d.pop(10)
print(d)
print(len(d))

Ion
Maria
Ion
Vasile
Gigel
Stefan
{1: 'Maria', 2: 'Ion', 3: 'Vasile', 4: 'Gigel', 5: 'Stefan', 6: 'Alex', 7: 'Gheorghe', 8: 'Irina', 9: 'Elena', 10: 'Matei', 11: 'Ionut'}
{1: 'Maria', 2: 'Ion', 3: 'Vasile', 4: 'Gigel', 5: 'Stefan', 6: 'Alex', 7: 'Gheorghe', 8: 'Irina', 9: 'Ionela', 10: 'Matei', 11: 'Ionut'}
11
{1: 'Maria', 2: 'Ion', 3: 'Vasile', 4: 'Gigel', 5: 'Stefan', 6: 'Alex', 7: 'Gheorghe', 8: 'Irina', 9: 'Ionela', 11: 'Ionut'}
10


# Funcții și clase
**Definirea blocurilor de instrucțiuni**

Blocurile de instrucțiuni în Python sunt delimitate prin spațiere (fie spații, fie tab-uri):


```
for i in range(0, 10):
  x = i * 10
  print(x)
```

Instrucțiunea anterioară reprezintă definirea unei bucle iterative ***for*** de la $1$ la $10$, în cadrul căreia se afișează valoarea variabile din interiorul for-ului, ***i***, înmulțită cu ***10***.
Cele două instrucțiuni:


```
x = i * 10
print(x)
```
sunt conținute în blocul de instrucțiuni ale buclei ***for***.

**Definirea funcțiilor**

Funcțiile se definesc în felul următor:



```
def foo(x, y):
  print(x)
  print(y * 5)
```

Similar cu exemplul anterior, fiecare funcție are corpul său definit într-un bloc de instrucțiuni.

**Notă**: Funcțiile din Python au implicit modul de transmitere al parametrilor prin referință.

**Definirea claselor**

Clasele în Python se definesc conform regulilor generale privind sintaxa/definirea blocurilor de instrucțiuni. De asemenea, sunt permise toate funcționalitățile de programare orientată-obiect din alte limbaje (e.g. C++), precum moștenirea sau polimorfismul.

```
class A:
  def __init__(self, a, b, c)
    self.a = a
    self.b = b
    self.c = c
  
  def print_vars(self):
    print(self.a)
    print(self.b)
    print(self.c)

class B(A):
  def __init__(self, a, b, c):
    super().__init__(a, b, c)
    self.d = 100

if __name__ == "__main__":
  ob1 = B(a=1, b=2, c=3)
  ob1.print_vars()
```

În exemplul anterior au fost definite două clase, **A** și **B**, unde clasa **B** moștenește clasa **A**. Clasa **B** automat moștenește toate variabilele și metodele clasei **A**. O particularitate a acestui limbaj este funcția $__init__$ a claselor. Aceasta este echivalentul constructorului din alte limbaje de programare. O altă particularitate este parametrul self. Acesta poate fi asemănat cu cuvântul-cheie this din C++ și are rolul de a marca faptul că funcția respectivă aparține unei instanțe specifice a clasei respective.

# Modulul numpy
Unul dintre cele mai utilizat module Python, în special în domeniul de Machine Learning este ***numpy*** (Numerical Python). Acesta este folosit pentru o varietate largă de operații matematice aplicate pe tipuri de date multidimensionale.
Acesta se instalează utilizând comanda ***pip***:

```
pip install numpy
```

Pentru a putea fi utilizat, trebuie întâi ca modulul să fie importat:

```
import numpy as np
```

**Notă**: în general, dezvoltatorii de aplicații Python importă modulul numpy utilizând aliasul np. Acest lucru nu este obligatoriu.

Tipurile de date folosite de numpy sunt echivalente cu unele tipuri de date din Python. Spre exemplu, o construcție precum:



```
x = [0, 0, 0, 0, 0]
```
este echivalentă cu:


```
import numpy as np

x = np.zeros(shape=(5,), dtype=np.uint8)
```

Se pot observa în schimb anumite diferențe:
*   valorile stocate în obiecte de tip numpy array trebuie să fie omogene (nu putem avea mai multe tipuri de obiecte într-un singur array)
*   un array numpy are constrângeri de tip de date, ceea ce implică un spor de eficiență d.p.d.v. al memoriei, respectiv al optimizărilor posibile.

**Indexarea elementelor**

Indexarea elementelor din array-uri numpy se face similar cu indexarea elementelor din array-uri clasice de Python. De exemplu:


```
x = [1, 2, 3, 4, 5]
print(x[2])  # va afisa elementul 3
```

este echivalent cu:



```
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=np.uint8)
print(x[2]) # va afisa tot elementul 3
```

Indexarea elementelor se modifică în schimb atunci când vorbim despre obiecte multidimensionale. Spre exemplu:



```
x1 = [[1, 2, 3], [4, 5, 6]]
print(x1[1][0]) # va afisa valoarea 4

import numpy as np
x2 = np.array(x1, dtype=np.uint8)  # initializarea lui x2 pe baza lui x1
print(x2[1, 0]) # va afisa valoarea 4

```

**Notă**: A se observa faptul că în cadrul ultimelor două exemple s-a inițializat obiectul de tip numpy array pe baza unei liste Python. Acest mod de inițializare a unui array este deseori util în sarcinile uzuale care implică manipularea array-urilor.

Un numpy array suportă de asemenea operații de ***list slicing***:

```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

print(x[:2, :2])

```
Acest exemplu va afișa toate elementele până la indexul 2 de pe prima dimensiune **și** respectiv până la indexul 2 de pe a doua dimensiune:


```
>>> x
array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [2, 3, 4, 5, 6],
       [1, 3, 5, 6, 7]], dtype=uint8)
>>> x[:2,:2]
array([[1, 2],
       [6, 7]], dtype=uint8)
```

De asemenea, se pot folosi diverse condiții asupra array-ului:


```
>>> print(x[x>3])
[4 5 6 7 8 9 4 5 6 5 6 7]
```

Acest exemplu afișează toate elementele din array-ul x care respectă condiția $x[i, j] > 3$.

**Operații matematice cu obiecte numpy array**

Una dintre operațiile de bază care se pot realiza cu obiecte numpy este înmulțirea cu un scalar:

```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

>>> x * 5
array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45,  0],
       [10, 15, 20, 25, 30],
       [ 5, 15, 25, 30, 35]], dtype=uint8)
```

De asemenea, se poate realiza înmulțirea element-cu-element:



```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

x2 = np.array([[1, 1, 0, 0, 0], [0, 0, 1, 2, 1], [1, 1, 1, 1, 0], [0, 0, 1, 1, 1]], dtype=np.uint8)
>>> np.multiply(x, x2)
array([[ 1,  2,  0,  0,  0],
       [ 0,  0,  8, 18,  0],
       [ 2,  3,  4,  5,  0],
       [ 0,  0,  5,  6,  7]], dtype=uint8)
```

Adunarea matricelor:
```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

x2 = np.array([[1, 1, 0, 0, 0], [0, 0, 1, 2, 1], [1, 1, 1, 1, 0], [0, 0, 1, 1, 1]], dtype=np.uint8)
>>> x + x2
array([[ 2,  3,  3,  4,  5],
       [ 6,  7,  9, 11,  1],
       [ 3,  4,  5,  6,  6],
       [ 1,  3,  6,  7,  8]], dtype=uint8)
```


Transpusa unei matrice:



```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

>>> x
array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [2, 3, 4, 5, 6],
       [1, 3, 5, 6, 7]], dtype=uint8)
>>> x.T
array([[1, 6, 2, 1],
       [2, 7, 3, 3],
       [3, 8, 4, 5],
       [4, 9, 5, 6],
       [5, 0, 6, 7]], dtype=uint8)

```

Înmulțirea matricelor:



```
import numpy as np

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 4, 5, 6], [1, 3, 5, 6, 7]], dtype=np.uint8)

x2 = np.array([[1, 1, 0, 0, 0], [0, 0, 1, 2, 1], [1, 1, 1, 1, 0], [0, 0, 1, 1, 1]], dtype=np.uint8)

>>> x.T @ x2
array([[ 3,  3,  9, 15,  7],
       [ 5,  5, 13, 20, 10],
       [ 7,  7, 17, 25, 13],
       [ 9,  9, 20, 29, 15],
       [11, 11, 13, 13,  7]], dtype=uint8)
```
**Note:**
- Atenție la dimensiunile matricelor care vor fi înmulțite.
- operatorul @ nu este singura metodă care poate fi folosită pentru înmulțirea matricelor.

Inversa unei matrice:



```
import numpy as np

x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]], dtype=np.float32)
>>> np.linalg.inv(x3)
array([[-0.6666667, -1.3333334,  1.       ],
       [-0.6666667,  3.6666667, -2.       ],
       [ 1.       , -2.       ,  1.       ]], dtype=float32)
```

Redimensionarea unei matrice:
```
import numpy as np
x2 = np.array([[1, 1, 0, 0, 0], [0, 0, 1, 2, 1], [1, 1, 1, 1, 0], [0, 0, 1, 1, 1]], dtype=np.uint8)

>>> x2
array([[1, 1, 0, 0, 0],
       [0, 0, 1, 2, 1],
       [1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1]], dtype=uint8)
>>> x2.reshape((5, 4))
array([[1, 1, 0, 0],
       [0, 0, 0, 1],
       [2, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]], dtype=uint8)

```
**Notă** Redimensionarea unei matrice este posibilă doar dacă se păstrează numărul total de elemente. În exemplul anterior, unde s-a făcut redimensionarea de la $4 \times 5$ la $5 \times 4$, numărul total de elemente a rămas $20$.


**Referință**: https://numpy.org/doc/stable/user/absolute_beginners.html



# Exerciții numpy

1.   Să se creeze un numpy array bidimensional $x$ de dimensiune $5 \times 5$ cu valori întregi aleatoare.
2.   Să se înlocuiască toate valorile pare din array-ul creat anterior cu 0.
3.   Să se calculeze inversa matricei
\begin{equation}
  A = \begin{bmatrix}
    2 & -1 & 1 \\
      5 & 2 & -3 \\
      2 & 1 & -1
  \end{bmatrix}
\end{equation}
4.   Să se rezolve sistemul de ecuații $Ax = B$, unde:
\begin{equation}
A = \begin{bmatrix}
      2 & -1 & 1 \\
      5 & 2 & -3 \\
      2 & 1 & -1
    \end{bmatrix}
\end{equation}

\begin{equation}
B = \begin{bmatrix}
      3 \\
      1 \\
      2
    \end{bmatrix}
\end{equation}
Sistemul se va rezolva prin calcul algebric.

5.   Să se rezolve același sistem, însă utilizând funcția dedicată **solve**.


In [9]:
import numpy as np

# ex1
x = np.random.randint(0, 100, size=(5, 5))
print("x=", x)

# ex2
x[x % 2 == 0] = 0
print("x=", x)

# ex3
A = np.array([[2, -1, 1], [5, 2, -3], [2, 1, -1]])
A_inv = np.linalg.inv(A)
print("A^-1 = ", A_inv)

# ex4
B = np.array([[3], [1], [2]])
x = np.dot(A_inv, B)
print("x = ", x)

# ex5
x = np.linalg.solve(A, B)
print("x = ", x)


x= [[14 89 55 98 12]
 [90 22  3 29  2]
 [ 0 62 61  4 59]
 [ 3 13 82 37  6]
 [78 17 89 53 58]]
x= [[ 0 89 55  0  0]
 [ 0  0  3 29  0]
 [ 0  0 61  0 59]
 [ 3 13  0 37  0]
 [ 0 17 89 53  0]]
A^-1 =  [[ 2.5000000e-01  4.4408921e-17  2.5000000e-01]
 [-2.5000000e-01 -1.0000000e+00  2.7500000e+00]
 [ 2.5000000e-01 -1.0000000e+00  2.2500000e+00]]
x =  [[1.25]
 [3.75]
 [4.25]]
x =  [[1.25]
 [3.75]
 [4.25]]


# Exerciții propuse


1.   Să se implementeze căutarea binară. (https://www.geeksforgeeks.org/binary-search/). Funcția implementată primește ca parametri șirul (ordonat crescător), respectiv elementul care se caută în șir și returnează indexul în șir al elementului, dacă acesta a fost găsit, respectiv -1 în caz contrar.
2.   Să se implementeze o funcție care returnează primele n elemente ale secvenței Fibonacci (1, 1, 2, 3, 5, 8, ...). Funcția primește ca parametru lungimea dorită a secvenței Fibonacci (n) și returnează secvența respectivă.
3.   Să se implementeze o funcție care calculează produsul elementelor unui șir. Funcția primește ca parametru șirul și returnează produsul elementelor.
4.   Să se implementeze o funcție care returnează inversul unui șir. Aceasta va primi ca parametru șirul pe care dorim să-l inversăm și va returna șirul inversat.
5.   Să se implementeze o funcție care verifică dacă un șir este palindrom. Funcția primește ca parametru un șir și returnează True dacă aceste este palindrom, respectiv False în caz contrar.



In [4]:
# Implementarea exercitiilor definite in sectiunea anterioara

# Exercitiul 1
def cautare_binara(sir, elem):

  l=0
  h=len(sir)
  x= int((h-l)/2)
  while sir[x]!=elem:
    if  elem>sir[x]:
      l=x
      x=int((h-x)/2)
    else:
      h=x
      x=int((x-l)/2)
  if h==l:
    return -1
  else:
    return x

sir_ordonat = [1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 15, 20, 25, 30, 32, 37, 50]
elem = 11
idx = cautare_binara(sir_ordonat, elem)
print(f"Valoarea {elem} se afla la pozitia {idx}") # Va afisa 8
elem2 = 10
idx2 = cautare_binara(sir_ordonat, elem2)
print(f"Valoarea {elem2} se afla la pozitia {idx2}") # Va afisa -1

##Exercitiul 2
def fibonacci(n):
  fib = [1,1]
  if n<=1:
    return fib[0];
  elif n==2:
    return fib;
  else:
    for i in range(2:n):
      fib.append (fib[-1]+fib[-2])
    return fib

n_secv = 3
fib = fibonacci(n_secv)
print(f"Sirul fibonacci de lungime {n_secv} este: {fib}") # Va afisa [1, 1, 2]

# Exercitiul 3
def prod_elem(sir):
  pass

sir_elemente = [1, 4, 2, 2, 1, 2]
prod_elemente = prod_elem(sir_elemente)
print(f"Produsul elementelor sirului este: {prod_elemente}") # Va afisa 32

# Exercitiul 4
def invers_sir(sir):
  pass

sir_de_inversat = [1, 2, 3, 4, 5]
sir_inv = invers_sir(sir_de_inversat)
print(f"Sirul inversat este: {sir_inv}") # Va afisa [5, 4, 3, 2, 1]

# Exercitiul 5
def palindrom(sir):
  pass

sir_p1 = [1, 2, 3, 2, 1]
sir_p2 = [1, 2, 3, 4, 5]

p1 = palindrom(sir_p1)
p2 = palindrom(sir_p2)
print(f"Sirul {sir_p1} palindrom: {p1}") # Va afisa True
print(f"Sirul {sir_p2} palindrom: {p2}") # Va afisa False

SyntaxError: invalid syntax (<ipython-input-4-df33640b6700>, line 37)

# Exerciții algebră liniară


1.   Se dau următoarele matrice

$$A = \begin{bmatrix} 12 & 23 & 38 & 65 \\ 32 & 22 & 12 & 44 \\ 33 & 12 & 67 & 11 \end{bmatrix}$$

$$B = \begin{bmatrix}11 & 12 & 13 \\ 20 & 21 & 22 \\ 30 & 31 & 32 \\ 40 & 41 & 42\end{bmatrix}$$

$$C = \begin{bmatrix}1 & 2 & 3 \\ 3 & 2 & 1 \\ 4 & 5 & 6\end{bmatrix}$$

Să se calculeze și afișeze:


*   $A^T + B$
*   $B^T + A$
*   $A - B^T$
*   $5 \times A^T$
*   $(AB)^T + I_3$
*   $C^{-1}$

2.  Se definește o matrice $A_{(4,5)}$ inițializată cu valori aleatorii. Să se afișeze folosind indexarea specifică numpy un bloc de elemente de dimensiune $2\times2$ la alegere. De exemplu, se poate afișa blocul de elemente de la $A_{(0,0)}$ la $A_{(1,1)}$: Astfel se obține o submatrice $A_1 = \begin{bmatrix} A_{00} & A_{01} \\ A_{10} & A_{11}\end{bmatrix}$.
3.  Să se adauge la matricea inițială definită anterior o coloană cu valori de 1.
4.  Să se adauge la matricea obținută în exercițiul anterior o linie cu valori de 2.
5.  Să se afișeze toate elementele de pe a doua linie a matricei obținută în exercițiul anterior.


In [13]:
# Implementarea exercitiilor definite in sectiunea anterioara
import numpy as np

A= np.array ([[12, 23, 38, 65],[32, 22, 12, 44],[33, 12, 67, 11]])
B = np.array([[11, 12 ,13],[20, 21, 22],[30, 31, 32],[40, 41, 42]])
C = np.array([[1, 2, 3], [3, 2, 1], [4, 5 ,6]])

# Exercitiul 1
print(A.T+B)
print(B.T+A)
print(A-B.T)
print(A.T*5)
print((A@B).T+np.eye(3))

# Exercitiul 2
A = np.random.randint(0,100, size=(4,5), dtype=np.uint8)
print(A)
print(A[:2,:2])
# Exercitiul 3
B= np.array([[1], [1], [1], [1]])

C=np.hstack((A,B))
print (C)
# Exercitiul 4
B=np.array([2, 2, 2, 2, 2, 2])
C= np.vstack((C,B))
print(C)
# Exercitiul 5
print(C[1,:])


[[ 23  44  46]
 [ 43  43  34]
 [ 68  43  99]
 [105  85  53]]
[[ 23  43  68 105]
 [ 44  43  43  85]
 [ 46  34  99  53]]
[[  1   3   8  25]
 [ 20   1 -19   3]
 [ 20 -10  35 -31]]
[[ 60 160 165]
 [115 110  60]
 [190  60 335]
 [325 220  55]]
[[4333. 2912. 3053.]
 [4470. 3023. 3176.]
 [4608. 3132. 3300.]]
[[61  9  8 22 63]
 [81 96 25 36 85]
 [39 77 99 92  3]
 [76 90 41 25 47]]
[[61  9]
 [81 96]]
[[61  9  8 22 63  1]
 [81 96 25 36 85  1]
 [39 77 99 92  3  1]
 [76 90 41 25 47  1]]
[[61  9  8 22 63  1]
 [81 96 25 36 85  1]
 [39 77 99 92  3  1]
 [76 90 41 25 47  1]
 [ 2  2  2  2  2  2]]
[81 96 25 36 85  1]
